package system

import (
	"bufio"
	"bytes"
	"context"
	"database/sql"
	"encoding/base64"
	"fmt"
	"github.com/tomasweigenast/srouter/internal/logging"
	"net"
	"net/url"
	"os"
	"os/exec"
	"strings"
	"text/template"
	"time"
)

const (
	stubbyBin     = "/usr/sbin/stubby"
	stubbyConfDir = "/etc/stubby"
	stubbyConf    = "/etc/stubby/stubby.yml"
	StubbyListen  = "127.0.0.1#5353"

	dnscryptBin     = "/usr/sbin/dnscrypt-proxy"
	dnscryptConfDir = "/etc/dnscrypt-proxy"
	dnscryptConf    = "/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
	dnscryptCache   = "/var/cache/dnscrypt-proxy"
	DnscryptListen  = "127.0.0.1#5454"
)

var dohLogger = logging.GetLogger("doh")

// DoHProvider describes a built-in encrypted DNS resolver.
type DoHProvider struct {
	ID          string
	Label       string
	Description string
	DoTAddrs    []string // IP addresses for stubby
	DoTName     string   // TLS hostname for stubby
	DoHName     string   // server_name in dnscrypt-proxy public list (builtins only)
	DoHURL      string   // HTTPS URL for custom providers (generates [static] stamp)
}

// BuiltinProviders is the list of supported encrypted DNS providers.
var BuiltinProviders = []DoHProvider{
	{
		ID: "cloudflare", Label: "Cloudflare", Description: "1.1.1.1 — fast, privacy-first",
		DoTAddrs: []string{"1.1.1.1", "1.0.0.1"}, DoTName: "cloudflare-dns.com", DoHName: "cloudflare",
	},
	{
		ID: "google", Label: "Google", Description: "8.8.8.8 — widely used",
		DoTAddrs: []string{"8.8.8.8", "8.8.4.4"}, DoTName: "dns.google", DoHName: "google",
	},
	{
		ID: "quad9", Label: "Quad9 (no filter)", Description: "9.9.9.9 — privacy-focused",
		DoTAddrs: []string{"9.9.9.9", "149.112.112.112"}, DoTName: "dns.quad9.net", DoHName: "quad9-doh-ip4-port443-nofilter-pri",
	},
	{
		ID: "adguard", Label: "AdGuard DNS", Description: "Blocks ads & tracking",
		DoTAddrs: []string{"94.140.14.14", "94.140.15.15"}, DoTName: "dns.adguard.com", DoHName: "adguard-dns-unfiltered-doh",
	},
	{
		ID: "custom", Label: "Custom…", Description: "Enter your own server details",
	},
}

// DoHConfig is the persisted user configuration (single row in doh_config).
type DoHConfig struct {
	Enabled          bool
	ProviderID       string // builtin provider ID or "custom"
	FallbackToPlain  bool
	StashedUpstreams string // comma-separated; internal use only
	CustomDoTIP      string // used when ProviderID == "custom"
	CustomDoTTLSName string
	CustomDoHURL     string // HTTPS DoH URL, e.g. https://dns.quad9.net/dns-query
}

// DoHStatus is the runtime state returned to the UI.
type DoHStatus struct {
	DoTInstalled bool
	DoHInstalled bool
	DoTRunning   bool
	DoHRunning   bool
	Config       DoHConfig
	Providers    []DoHProvider
}

// AnyInstalled reports whether at least one encrypted DNS tool is present.
func (s DoHStatus) AnyInstalled() bool { return s.DoTInstalled || s.DoHInstalled }

var stubbyTmpl = template.Must(template.New("stubby").Parse(
	`## Generated by srouter — do not edit manually
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
listen_addresses:
  - 127.0.0.1@5353
idle_timeout: 10000
upstream_recursive_servers:
{{- range .DoTAddrs}}
  - address_data: {{.}}
    tls_auth_name: "{{$.DoTName}}"
    tls_port: 853
{{- end}}
`))

// dnscryptBuiltinTmpl is used for builtin providers (uses public resolver list).
var dnscryptBuiltinTmpl = template.Must(template.New("dnscrypt-builtin").Parse(
	`## Generated by srouter — do not edit manually

listen_addresses = ['127.0.0.1:5454']
server_names = ['{{.DoHName}}']

fallback_resolvers = ['9.9.9.9:53', '8.8.8.8:53']
ignore_system_dns = true
cache = false
log_level = 2

[sources]
  [sources.public-resolvers]
  urls = ['https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
          'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md']
  cache_file = '` + dnscryptCache + `/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
`))

// dnscryptCustomTmpl is used for custom providers (uses [static] with a generated stamp).
var dnscryptCustomTmpl = template.Must(template.New("dnscrypt-custom").Parse(
	`## Generated by srouter — do not edit manually

listen_addresses = ['127.0.0.1:5454']
server_names = ['custom']

fallback_resolvers = ['9.9.9.9:53', '8.8.8.8:53']
ignore_system_dns = true
cache = false
log_level = 2

[static]
  [static.custom]
  stamp = '{{.Stamp}}'
`))

// GetDoHConfig reads DoH configuration from the database.
func GetDoHConfig(db *sql.DB) (DoHConfig, error) {
	var cfg DoHConfig
	var enabled, fallback int
	err := db.QueryRow(`
		SELECT enabled, provider, fallback_to_plain, stashed_upstreams,
		       custom_dot_ip, custom_dot_tls_name, custom_doh_server
		FROM doh_config WHERE id = 1`).
		Scan(&enabled, &cfg.ProviderID, &fallback, &cfg.StashedUpstreams,
			&cfg.CustomDoTIP, &cfg.CustomDoTTLSName, &cfg.CustomDoHURL)
	if err != nil {
		return DoHConfig{}, fmt.Errorf("get doh config: %w", err)
	}
	cfg.Enabled = enabled == 1
	cfg.FallbackToPlain = fallback == 1
	return cfg, nil
}

// SaveDoHConfig persists DoH configuration to the database.
func SaveDoHConfig(db *sql.DB, cfg DoHConfig) error {
	enabled, fallback := 0, 0
	if cfg.Enabled {
		enabled = 1
	}
	if cfg.FallbackToPlain {
		fallback = 1
	}
	_, err := db.Exec(`
		UPDATE doh_config
		SET enabled=?, provider=?, fallback_to_plain=?, stashed_upstreams=?,
		    custom_dot_ip=?, custom_dot_tls_name=?, custom_doh_server=?
		WHERE id=1`,
		enabled, cfg.ProviderID, fallback, cfg.StashedUpstreams,
		cfg.CustomDoTIP, cfg.CustomDoTTLSName, cfg.CustomDoHURL)
	if err != nil {
		return fmt.Errorf("save doh config: %w", err)
	}
	return nil
}

// GetDoHStatus returns current configuration and runtime state.
func GetDoHStatus(db *sql.DB) (DoHStatus, error) {
	cfg, err := GetDoHConfig(db)
	if err != nil {
		return DoHStatus{}, err
	}
	return DoHStatus{
		DoTInstalled: IsStubbyInstalled(),
		DoHInstalled: IsDNSCryptInstalled(),
		DoTRunning:   IsStubbyRunning(),
		DoHRunning:   IsDNSCryptRunning(),
		Config:       cfg,
		Providers:    BuiltinProviders,
	}, nil
}

// IsStubbyInstalled reports whether the stubby binary is present.
func IsStubbyInstalled() bool {
	if _, err := exec.LookPath("stubby"); err == nil {
		return true
	}
	for _, p := range []string{stubbyBin, "/usr/bin/stubby"} {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	return false
}

// IsStubbyRunning reports whether the stubby service is running.
func IsStubbyRunning() bool {
	return exec.Command("rc-service", "stubby", "status").Run() == nil
}

// IsDNSCryptInstalled reports whether the dnscrypt-proxy binary is present.
func IsDNSCryptInstalled() bool {
	if _, err := exec.LookPath("dnscrypt-proxy"); err == nil {
		return true
	}
	for _, p := range []string{dnscryptBin, "/usr/bin/dnscrypt-proxy"} {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	return false
}

// IsDNSCryptRunning reports whether the dnscrypt-proxy service is running.
func IsDNSCryptRunning() bool {
	return exec.Command("rc-service", "dnscrypt-proxy", "status").Run() == nil
}

// EnableEncryptedDNS configures and starts both stubs, then sets dnsmasq to strict-order.
func EnableEncryptedDNS(db *sql.DB, cfg DoHConfig) error {
	// Stash current plain upstream servers before overwriting.
	current, err := GetUpstreamServers()
	if err != nil {
		dohLogger.Warn("could not read current upstream servers before enabling encrypted DNS", "err", err)
	}
	cfg.StashedUpstreams = stashUpstreams(current, cfg.StashedUpstreams)
	cfg.Enabled = true
	if err := SaveDoHConfig(db, cfg); err != nil {
		return err
	}

	p := resolveProvider(cfg)

	if IsStubbyInstalled() {
		if err := writeStubbyConfig(p); err != nil {
			return err
		}
		if err := exec.Command("rc-service", "stubby", "start").Run(); err != nil {
			dohLogger.Warn("start stubby", "err", err)
		}
		_ = exec.Command("rc-update", "add", "stubby", "default").Run()
	}

	if IsDNSCryptInstalled() {
		if err := writeDoHProxyConfig(p); err != nil {
			return err
		}
		if err := exec.Command("rc-service", "dnscrypt-proxy", "start").Run(); err != nil {
			dohLogger.Warn("start dnscrypt-proxy", "err", err)
		}
		_ = exec.Command("rc-update", "add", "dnscrypt-proxy", "default").Run()
	}

	// Build ordered server list: DoT → DoH → plain.
	servers := buildEncryptedServers(cfg)
	if err := SetUpstreamServers(servers); err != nil {
		return fmt.Errorf("set dnsmasq upstreams: %w", err)
	}
	if err := setStrictOrder(true); err != nil {
		return err
	}
	return ReloadDNSMasq()
}

// DisableEncryptedDNS stops both stubs and restores plain upstream servers.
func DisableEncryptedDNS(db *sql.DB) error {
	cfg, err := GetDoHConfig(db)
	if err != nil {
		return err
	}

	stopAllEncryptedDNS()

	if err := setStrictOrder(false); err != nil {
		return err
	}

	restored := restoreUpstreams(cfg.StashedUpstreams)
	if err := SetUpstreamServers(restored); err != nil {
		return fmt.Errorf("restore upstream servers: %w", err)
	}

	cfg.Enabled = false
	if err := SaveDoHConfig(db, cfg); err != nil {
		return err
	}
	return ReloadDNSMasq()
}

// writeStubbyConfig renders and writes the stubby YAML config.
func writeStubbyConfig(p DoHProvider) error {
	if err := os.MkdirAll(stubbyConfDir, 0o755); err != nil {
		return fmt.Errorf("create stubby config dir: %w", err)
	}
	var buf bytes.Buffer
	if err := stubbyTmpl.Execute(&buf, p); err != nil {
		return fmt.Errorf("render stubby config: %w", err)
	}
	if err := os.WriteFile(stubbyConf, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write stubby config: %w", err)
	}
	return nil
}

// writeDoHProxyConfig renders and writes the dnscrypt-proxy TOML config.
// For custom providers it generates a DoH stamp from the URL; for builtins it
// uses the public resolver list with the server_names entry.
func writeDoHProxyConfig(p DoHProvider) error {
	if err := os.MkdirAll(dnscryptConfDir, 0o755); err != nil {
		return fmt.Errorf("create dnscrypt-proxy config dir: %w", err)
	}
	if err := os.MkdirAll(dnscryptCache, 0o755); err != nil {
		return fmt.Errorf("create dnscrypt-proxy cache dir: %w", err)
	}

	var (
		buf bytes.Buffer
		err error
	)
	if p.DoHURL != "" {
		stamp, stampErr := buildDoHStamp(p.DoHURL)
		if stampErr != nil {
			return fmt.Errorf("build doh stamp: %w", stampErr)
		}
		err = dnscryptCustomTmpl.Execute(&buf, struct{ Stamp string }{stamp})
	} else {
		err = dnscryptBuiltinTmpl.Execute(&buf, p)
	}
	if err != nil {
		return fmt.Errorf("render dnscrypt-proxy config: %w", err)
	}
	if err := os.WriteFile(dnscryptConf, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write dnscrypt-proxy config: %w", err)
	}
	return nil
}

// buildDoHStamp generates a dnscrypt-proxy stamp from a DoH HTTPS URL.
// Stamp format: sdns://Ag<base64url(props[8] + LP(addr) + LP(hash) + LP(host) + LP(path))>
func buildDoHStamp(rawURL string) (string, error) {
	u, err := url.Parse(rawURL)
	if err != nil {
		return "", fmt.Errorf("invalid DoH URL: %w", err)
	}
	if u.Scheme != "https" {
		return "", fmt.Errorf("DoH URL must use https://")
	}
	hostname := u.Hostname()
	path := u.Path
	if path == "" {
		path = "/dns-query"
	}

	var buf bytes.Buffer
	buf.WriteByte(0x02)                        // protocol: DoH
	buf.Write([]byte{0, 0, 0, 0, 0, 0, 0, 0}) // props: default (no DNSSEC/log/filter flags)
	writeLP(&buf, nil)                         // addr: empty (resolved from hostname)
	writeLP(&buf, nil)                         // hash: empty (no cert pinning)
	writeLP(&buf, []byte(hostname))
	writeLP(&buf, []byte(path))

	return "sdns://" + base64.RawURLEncoding.EncodeToString(buf.Bytes()), nil
}

func writeLP(buf *bytes.Buffer, data []byte) {
	buf.WriteByte(byte(len(data)))
	buf.Write(data)
}

// setStrictOrder adds or removes the strict-order directive in dnsmasq.conf.
func setStrictOrder(enable bool) error {
	data, err := os.ReadFile(dnsmasqConf)
	if err != nil {
		return fmt.Errorf("read dnsmasq.conf: %w", err)
	}

	var lines []string
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "strict-order" {
			continue // always remove existing entry; re-add below if needed
		}
		lines = append(lines, line)
	}
	if enable {
		lines = append([]string{"strict-order"}, lines...)
	}

	out := strings.Join(lines, "\n")
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	if err := os.WriteFile(dnsmasqConf, []byte(out), 0o644); err != nil {
		return fmt.Errorf("write dnsmasq.conf: %w", err)
	}
	return nil
}

// resolveProvider returns the DoHProvider for the given config (builtin or custom).
func resolveProvider(cfg DoHConfig) DoHProvider {
	if cfg.ProviderID != "custom" {
		for _, p := range BuiltinProviders {
			if p.ID == cfg.ProviderID {
				return p
			}
		}
	}
	return DoHProvider{
		ID:       "custom",
		Label:    "Custom",
		DoTAddrs: []string{cfg.CustomDoTIP},
		DoTName:  cfg.CustomDoTTLSName,
		DoHURL:   cfg.CustomDoHURL,
	}
}

// buildEncryptedServers returns the dnsmasq server list: DoT → DoH → plain.
func buildEncryptedServers(cfg DoHConfig) []UpstreamServer {
	var servers []UpstreamServer
	if IsStubbyInstalled() {
		servers = append(servers, UpstreamServer{Address: StubbyListen})
	}
	if IsDNSCryptInstalled() {
		servers = append(servers, UpstreamServer{Address: DnscryptListen})
	}
	if cfg.FallbackToPlain {
		for _, addr := range restoreUpstreams(cfg.StashedUpstreams) {
			servers = append(servers, addr)
		}
	}
	return servers
}

// stopAllEncryptedDNS stops both stubs, ignoring errors.
func stopAllEncryptedDNS() {
	for _, svc := range []string{"stubby", "dnscrypt-proxy"} {
		if out, err := exec.Command("rc-service", svc, "stop").CombinedOutput(); err != nil {
			dohLogger.Debug("stop encrypted dns service", "service", svc, "output", string(out), "err", err)
		}
		_ = exec.Command("rc-update", "del", svc).Run()
	}
}

// stashUpstreams returns comma-separated upstream IPs, excluding stub addresses.
func stashUpstreams(current []UpstreamServer, previous string) string {
	stubAddrs := map[string]bool{StubbyListen: true, DnscryptListen: true}
	var addrs []string
	for _, s := range current {
		if !stubAddrs[s.Address] {
			addrs = append(addrs, s.Address)
		}
	}
	if len(addrs) == 0 {
		return previous
	}
	return strings.Join(addrs, ",")
}

// TestEncryptedLookup resolves hostname via each local stub and returns the results.
func TestEncryptedLookup(hostname string) (EncryptedLookupResult, error) {
	var r EncryptedLookupResult
	r.DoTAddrs, r.DoTLatency, r.DoTErr = lookupViaPort(hostname, "5353")
	r.DoHAddrs, r.DoHLatency, r.DoHErr = lookupViaPort(hostname, "5454")
	return r, nil
}

func lookupViaPort(hostname, port string) (addrs []string, latency string, errStr string) {
	resolver := &net.Resolver{
		PreferGo: true,
		Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
			d := net.Dialer{Timeout: 3 * time.Second}
			return d.DialContext(ctx, "udp", "127.0.0.1:"+port)
		},
	}
	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 4*time.Second)
	defer cancel()
	result, err := resolver.LookupHost(ctx, hostname)
	latency = time.Since(start).Round(time.Millisecond).String()
	if err != nil {
		errStr = err.Error()
		return
	}
	addrs = result
	return
}

// restoreUpstreams converts a stashed comma-separated string back to a slice.
func restoreUpstreams(stashed string) []UpstreamServer {
	parts := strings.Split(stashed, ",")
	out := make([]UpstreamServer, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, UpstreamServer{Address: p})
		}
	}
	if len(out) == 0 {
		return []UpstreamServer{{Address: "1.1.1.1"}, {Address: "8.8.8.8"}}
	}
	return out
}
